language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install pipenv pew
  - pipenv install --dev --ignore-pipfile
script:
  - pipenv run flake8
  # TODO write some tests and run them here
